<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StockTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('stock')->delete();
        
        \DB::table('stock')->insert(array (
            0 => 
            array (
                'stock_id' => 33,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 8,
                'tujuan_id' => 0,
                'product_amount' => 100,
                'type' => 1,
                'datetime' => '2021-02-26 01:17:48',
                'ending_amount' => 100,
            ),
            1 => 
            array (
                'stock_id' => 34,
                'user_id' => 1,
                'shelf_id' => 9,
                'product_id' => 8,
                'tujuan_id' => 0,
                'product_amount' => 100,
                'type' => 1,
                'datetime' => '2021-02-26 01:17:56',
                'ending_amount' => 200,
            ),
            2 => 
            array (
                'stock_id' => 35,
                'user_id' => 1,
                'shelf_id' => 9,
                'product_id' => 8,
                'tujuan_id' => 0,
                'product_amount' => 50,
                'type' => 0,
                'datetime' => '2021-02-26 01:18:21',
                'ending_amount' => 150,
            ),
            3 => 
            array (
                'stock_id' => 36,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => 0,
                'product_amount' => 10,
                'type' => 1,
                'datetime' => '2021-03-01 16:48:39',
                'ending_amount' => 10,
            ),
            4 => 
            array (
                'stock_id' => 37,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => 0,
                'product_amount' => 10,
                'type' => 1,
                'datetime' => '2021-03-01 16:50:06',
                'ending_amount' => 20,
            ),
            5 => 
            array (
                'stock_id' => 38,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 12,
                'tujuan_id' => 0,
                'product_amount' => 5,
                'type' => 1,
                'datetime' => '2021-03-01 17:27:43',
                'ending_amount' => 5,
            ),
            6 => 
            array (
                'stock_id' => 39,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => 0,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 16:45:30',
                'ending_amount' => 19,
            ),
            7 => 
            array (
                'stock_id' => 40,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 16:52:22',
                'ending_amount' => 18,
            ),
            8 => 
            array (
                'stock_id' => 41,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 17:08:39',
                'ending_amount' => 17,
            ),
            9 => 
            array (
                'stock_id' => 42,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 17:08:59',
                'ending_amount' => 16,
            ),
            10 => 
            array (
                'stock_id' => 43,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 17:09:46',
                'ending_amount' => 15,
            ),
            11 => 
            array (
                'stock_id' => 44,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 17:11:00',
                'ending_amount' => 14,
            ),
            12 => 
            array (
                'stock_id' => 45,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 17:12:33',
                'ending_amount' => 13,
            ),
            13 => 
            array (
                'stock_id' => 46,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 17:12:50',
                'ending_amount' => 12,
            ),
            14 => 
            array (
                'stock_id' => 47,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 17:16:29',
                'ending_amount' => 11,
            ),
            15 => 
            array (
                'stock_id' => 48,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 17:19:22',
                'ending_amount' => 10,
            ),
            16 => 
            array (
                'stock_id' => 49,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 17:19:31',
                'ending_amount' => 9,
            ),
            17 => 
            array (
                'stock_id' => 50,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => 4,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 17:20:17',
                'ending_amount' => 8,
            ),
            18 => 
            array (
                'stock_id' => 51,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => 7,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 18:00:13',
                'ending_amount' => 7,
            ),
            19 => 
            array (
                'stock_id' => 52,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 18:10:36',
                'ending_amount' => 8,
            ),
            20 => 
            array (
                'stock_id' => 53,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => 6,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 18:12:36',
                'ending_amount' => 7,
            ),
            21 => 
            array (
                'stock_id' => 54,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 12,
                'type' => 1,
                'datetime' => '2022-07-31 18:19:23',
                'ending_amount' => 19,
            ),
            22 => 
            array (
                'stock_id' => 55,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 18:19:58',
                'ending_amount' => 18,
            ),
            23 => 
            array (
                'stock_id' => 56,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 18:20:42',
                'ending_amount' => 17,
            ),
            24 => 
            array (
                'stock_id' => 57,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 7,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 18:21:52',
                'ending_amount' => 16,
            ),
            25 => 
            array (
                'stock_id' => 58,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 18:22:04',
                'ending_amount' => 15,
            ),
            26 => 
            array (
                'stock_id' => 59,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => 7,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 18:22:34',
                'ending_amount' => 14,
            ),
            27 => 
            array (
                'stock_id' => 60,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 18:25:08',
                'ending_amount' => 13,
            ),
            28 => 
            array (
                'stock_id' => 61,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => 6,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 18:25:13',
                'ending_amount' => 12,
            ),
            29 => 
            array (
                'stock_id' => 62,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => 6,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 18:25:31',
                'ending_amount' => 11,
            ),
            30 => 
            array (
                'stock_id' => 63,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 18:26:29',
                'ending_amount' => 12,
            ),
            31 => 
            array (
                'stock_id' => 64,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 18:48:03',
                'ending_amount' => 13,
            ),
            32 => 
            array (
                'stock_id' => 65,
                'user_id' => 1,
                'shelf_id' => 9,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 18:48:20',
                'ending_amount' => 14,
            ),
            33 => 
            array (
                'stock_id' => 66,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 19:56:17',
                'ending_amount' => 15,
            ),
            34 => 
            array (
                'stock_id' => 67,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 19:56:27',
                'ending_amount' => 14,
            ),
            35 => 
            array (
                'stock_id' => 68,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 19:56:41',
                'ending_amount' => 15,
            ),
            36 => 
            array (
                'stock_id' => 69,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 19:56:51',
                'ending_amount' => 14,
            ),
            37 => 
            array (
                'stock_id' => 70,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 21:44:24',
                'ending_amount' => 15,
            ),
            38 => 
            array (
                'stock_id' => 71,
                'user_id' => 1,
                'shelf_id' => 9,
                'product_id' => 13,
                'tujuan_id' => 6,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 21:46:21',
                'ending_amount' => 14,
            ),
            39 => 
            array (
                'stock_id' => 72,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 11,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 21:51:22',
                'ending_amount' => 15,
            ),
            40 => 
            array (
                'stock_id' => 73,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => 11,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 21:51:51',
                'ending_amount' => 16,
            ),
            41 => 
            array (
                'stock_id' => 74,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 11,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 21:52:22',
                'ending_amount' => 17,
            ),
            42 => 
            array (
                'stock_id' => 75,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 11,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 21:53:39',
                'ending_amount' => 18,
            ),
            43 => 
            array (
                'stock_id' => 76,
                'user_id' => 1,
                'shelf_id' => 7,
                'product_id' => 13,
                'tujuan_id' => 11,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 21:57:52',
                'ending_amount' => 19,
            ),
            44 => 
            array (
                'stock_id' => 77,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 11,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 21:58:14',
                'ending_amount' => 20,
            ),
            45 => 
            array (
                'stock_id' => 78,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 22:00:17',
                'ending_amount' => 21,
            ),
            46 => 
            array (
                'stock_id' => 79,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 7,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 22:01:00',
                'ending_amount' => 20,
            ),
            47 => 
            array (
                'stock_id' => 80,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 6,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 22:02:33',
                'ending_amount' => 19,
            ),
            48 => 
            array (
                'stock_id' => 81,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 7,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 22:03:34',
                'ending_amount' => 18,
            ),
            49 => 
            array (
                'stock_id' => 82,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 6,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 22:19:44',
                'ending_amount' => 17,
            ),
            50 => 
            array (
                'stock_id' => 83,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 22:22:25',
                'ending_amount' => 18,
            ),
            51 => 
            array (
                'stock_id' => 84,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 267,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 22:23:58',
                'ending_amount' => 19,
            ),
            52 => 
            array (
                'stock_id' => 85,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 6,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 22:24:26',
                'ending_amount' => 18,
            ),
            53 => 
            array (
                'stock_id' => 86,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 7,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 22:26:49',
                'ending_amount' => 17,
            ),
            54 => 
            array (
                'stock_id' => 87,
                'user_id' => 1,
                'shelf_id' => 9,
                'product_id' => 13,
                'tujuan_id' => 0,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 22:27:28',
                'ending_amount' => 18,
            ),
            55 => 
            array (
                'stock_id' => 88,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 0,
                'product_amount' => 1,
                'type' => 1,
                'datetime' => '2022-07-31 22:30:14',
                'ending_amount' => 19,
            ),
            56 => 
            array (
                'stock_id' => 89,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 6,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 22:30:31',
                'ending_amount' => 18,
            ),
            57 => 
            array (
                'stock_id' => 90,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 6,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 22:33:28',
                'ending_amount' => 17,
            ),
            58 => 
            array (
                'stock_id' => 91,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => NULL,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 22:33:40',
                'ending_amount' => 16,
            ),
            59 => 
            array (
                'stock_id' => 92,
                'user_id' => 1,
                'shelf_id' => 8,
                'product_id' => 13,
                'tujuan_id' => 6,
                'product_amount' => 1,
                'type' => 0,
                'datetime' => '2022-07-31 22:33:44',
                'ending_amount' => 15,
            ),
        ));
        
        
    }
}